apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: example-for-computate
commonLabels:
  app: example-for-computate
resources:
- deploy.yaml
- namespace.yaml
- service.yaml
- route.yaml
